name: Attach Package on Release

on:
  release:
    types: [published]

env:
    UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
    UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}

jobs:
  build:
      name: Build
      runs-on: ubuntu-20.04
      concurrency:
        group: build-a-${{ github.ref }}
        cancel-in-progress: true
      steps:
          - name: Checkout code
            uses: actions/checkout@v3
            with:
              lfs: true
          - uses: actions/cache@v3
            with:
              path: Library
              key: Library-build
              restore-keys: Library-build
          - uses: game-ci/unity-builder@v2
            with:
              unityVersion: 2022.3.4f1
              buildMethod: Inworld.Editors.UnityPackageExporter.ExportFull
          - name: upload-artifact
            uses: actions/upload-artifact@v3
            with:
              name: InworldAI.Full
              path: Build/
          - name: Discard changes
            run: |
              git restore --staged .
              git checkout .
              git clean -fd
          - uses: game-ci/unity-builder@v2
            with:
              unityVersion: 2022.3.4f1
              buildMethod: Inworld.Editors.UnityPackageExporter.Lite
          - name: upload-artifact
            uses: actions/upload-artifact@v3
            with:
              name: InworldAI.Lite
              path: Build/              
          - name: Discard changes
            run: |
              git restore --staged .
              git checkout .
              git clean -fd          
              
  attach-to-release:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Download SDK Full
      uses: actions/download-artifact@v3
      with:
        name: InworldAI.Full
        path: Build/

    - name: Download SDK Lite
      uses: actions/download-artifact@v3
      with:
        name: InworldAI.Lite
        path: Build/
    
    - name: Rename packages with release tag
      run: |
        TAG_NAME=${GITHUB_REF/refs\/tags\//}
        mv Build/InworldAI.Full.unitypackage Build/InworldAI.Full.$TAG_NAME.unitypackage
        mv Build/InworldAI.Lite.unitypackage Build/InworldAI.Lite$TAG_NAME.unitypackage
    
    - name: Attach Full package to release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Build/InworldAI.Full.${{ github.ref/refs/tags/ }}.unitypackage

    - name: Attach Lite package to release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Build/InworldAI.Lite.${{ github.ref/refs/tags/ }}.unitypackage

