  name: Build

  on:
    workflow_dispatch:
    pull_request_review:
      types:
        - submitted

        
  env:
    UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
    UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}

  jobs:   
    build:
      name: Build
      runs-on: ubuntu-20.04
      concurrency:
        group: build-a-${{ github.ref }}
        cancel-in-progress: true
      steps:
          - name: Checkout code
            uses: actions/checkout@v3
            with:
              lfs: true              
          - uses: actions/cache@v3
            with:
              path: Library
              key: Library-build
              restore-keys: Library-build

          - uses: game-ci/unity-builder@v2
            with:
              unityVersion: 2022.3.12f1
              buildMethod: Inworld.Editors.UnityPackageExporter.ExportFull
          - name: upload-artifact
            uses: actions/upload-artifact@v3
            with:
              name: InworldAI.Full
              path: Build/

          - uses: game-ci/unity-builder@v2
            with:
              unityVersion: 2022.3.12f1
              buildMethod: Inworld.Editors.UnityPackageExporter.Lite
          - name: upload-artifact
            uses: actions/upload-artifact@v3
            with:
              name: InworldAI.Lite
              path: Build/      
