name: Check license header

on:
  pull_request:
    branches: [main]

jobs:
  check_header:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Verify header
      uses: marketplace/actions/license-eye-header@v1
      with:
        header: |
          /*************************************************************************************************
          * Copyright 2022 Theai, Inc. (DBA Inworld)
          *
          * Use of this source code is governed by the Inworld.ai Software Development Kit License Agreement
          * that can be found in the LICENSE.md file or at https://www.inworld.ai/sdk-license
          *************************************************************************************************/
